from flask import Flask

from app.config import Config
from app.extensions import db, migrate, socketio, login_manager


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    if not app.config.get("TESTING") and not app.config.get("SECRET_KEY"):
        raise RuntimeError("SECRET_KEY must be set. It is auto-generated by entrypoint.sh at deploy time.")

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    socketio.init_app(app, cors_allowed_origins="*")

    from app.auth.routes import auth_bp
    from app.chat.routes import chat_bp

    app.register_blueprint(auth_bp, url_prefix="/api/auth")
    app.register_blueprint(chat_bp, url_prefix="/api")

    from app.chat import events  # noqa: F401 - registers SocketIO handlers

    from app.errors import register_error_handlers
    register_error_handlers(app)

    return app
