import os


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", "")  # Auto-generated by entrypoint.sh at deploy time
    SQLALCHEMY_DATABASE_URI = os.environ.get(
        "DATABASE_URL", "REDACTED_POSTGRESQL_URI"
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    DOMAIN = os.environ.get("DOMAIN", "localhost")
    PREFERRED_URL_SCHEME = "https"

    GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")
    GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "")

    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

    ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "")


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
    SECRET_KEY = "test-secret-key"
    ADMIN_PASSWORD = "test-admin-password"
