import os


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", "")  # Auto-generated by entrypoint.sh at deploy time
    SQLALCHEMY_DATABASE_URI = os.environ.get(
        "DATABASE_URL", "REDACTED_SECRET"
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")
    GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "")

    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

    OAUTHLIB_INSECURE_TRANSPORT = os.environ.get("OAUTHLIB_INSECURE_TRANSPORT", "0")


class TestConfig(Config):
    TESTING = True
    SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
    SECRET_KEY = "test-secret-key"
